// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lcp/service/elc/v1/query.proto

package elc

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/ibc-go/v4/modules/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryClientRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *QueryClientRequest) Reset()         { *m = QueryClientRequest{} }
func (m *QueryClientRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClientRequest) ProtoMessage()    {}
func (*QueryClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b220343112c27a37, []int{0}
}
func (m *QueryClientRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClientRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClientRequest.Merge(m, src)
}
func (m *QueryClientRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClientRequest proto.InternalMessageInfo

type QueryClientResponse struct {
	// light client state
	ClientState *types.Any `protobuf:"bytes,1,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty" yaml:"client_state"`
	// consensus state associated with the client that corresponds to a given
	// height.
	ConsensusState *types.Any `protobuf:"bytes,2,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty" yaml:"consensus_state"`
}

func (m *QueryClientResponse) Reset()         { *m = QueryClientResponse{} }
func (m *QueryClientResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClientResponse) ProtoMessage()    {}
func (*QueryClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b220343112c27a37, []int{1}
}
func (m *QueryClientResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClientResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClientResponse.Merge(m, src)
}
func (m *QueryClientResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClientResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryClientRequest)(nil), "lcp.service.elc.v1.QueryClientRequest")
	proto.RegisterType((*QueryClientResponse)(nil), "lcp.service.elc.v1.QueryClientResponse")
}

func init() { proto.RegisterFile("lcp/service/elc/v1/query.proto", fileDescriptor_b220343112c27a37) }

var fileDescriptor_b220343112c27a37 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbd, 0x4e, 0xeb, 0x30,
	0x14, 0x4e, 0xae, 0x74, 0xab, 0xd6, 0xbd, 0xba, 0x57, 0x72, 0xab, 0x0b, 0x04, 0xc9, 0x41, 0x19,
	0xa0, 0x93, 0xad, 0x96, 0xad, 0x4c, 0x14, 0x09, 0x89, 0x0d, 0xc2, 0x54, 0x16, 0xe4, 0xb8, 0x26,
	0x8d, 0xe4, 0xc6, 0x69, 0x7e, 0x2a, 0xe5, 0x0d, 0x18, 0x79, 0x84, 0x3e, 0x4e, 0x07, 0x86, 0x8e,
	0x4c, 0x15, 0xb4, 0x0b, 0x73, 0x9f, 0x00, 0xc5, 0x0e, 0x3f, 0x55, 0x25, 0xd8, 0x7c, 0xce, 0xf9,
	0xbe, 0xef, 0x9c, 0xef, 0xf8, 0x00, 0x24, 0x58, 0x44, 0x12, 0x1e, 0x4f, 0x02, 0xc6, 0x09, 0x17,
	0x8c, 0x4c, 0xda, 0x64, 0x9c, 0xf1, 0x38, 0xc7, 0x51, 0x2c, 0x53, 0x09, 0xa1, 0x60, 0x11, 0x2e,
	0xeb, 0x98, 0x0b, 0x86, 0x27, 0x6d, 0xab, 0xe9, 0x4b, 0x5f, 0xaa, 0x32, 0x29, 0x5e, 0x1a, 0x69,
	0xed, 0xf9, 0x52, 0xfa, 0x82, 0x13, 0x15, 0x79, 0xd9, 0x1d, 0xa1, 0x61, 0x29, 0x62, 0xd9, 0x81,
	0xc7, 0x08, 0x93, 0x31, 0x27, 0x4c, 0x04, 0x3c, 0x4c, 0x8b, 0x26, 0xfa, 0xa5, 0x01, 0xce, 0x09,
	0x80, 0x57, 0x45, 0xd3, 0x33, 0x95, 0x74, 0xf9, 0x38, 0xe3, 0x49, 0x0a, 0xf7, 0x41, 0x4d, 0xa3,
	0x6e, 0x83, 0xc1, 0xae, 0x79, 0x60, 0xb6, 0x6a, 0x6e, 0x55, 0x27, 0x2e, 0x06, 0xdd, 0xea, 0xfd,
	0xd4, 0x36, 0x5e, 0xa7, 0xb6, 0xe1, 0x3c, 0x9a, 0xa0, 0xb1, 0xc1, 0x4e, 0x22, 0x19, 0x26, 0x1c,
	0x5e, 0x82, 0x3f, 0x25, 0x3d, 0x49, 0x69, 0xca, 0x95, 0x42, 0xbd, 0xd3, 0xc4, 0x7a, 0x4e, 0xfc,
	0x3e, 0x27, 0x3e, 0x0d, 0xf3, 0xde, 0xce, 0x7a, 0x61, 0x37, 0x72, 0x3a, 0x12, 0x5d, 0xe7, 0x2b,
	0xc7, 0x71, 0xeb, 0x3a, 0xbc, 0x2e, 0x22, 0xd8, 0x07, 0xff, 0x58, 0x21, 0x1d, 0x26, 0x59, 0x52,
	0x8a, 0xfe, 0xfa, 0x46, 0xd4, 0x5a, 0x2f, 0xec, 0xff, 0xa5, 0xe8, 0x26, 0xcd, 0x71, 0xff, 0x7e,
	0x64, 0x94, 0xf4, 0xa7, 0x9d, 0x8e, 0x07, 0x7e, 0x2b, 0x37, 0xb0, 0x0f, 0x2a, 0xda, 0x11, 0x3c,
	0xc4, 0xdb, 0xbf, 0x80, 0xb7, 0x17, 0x66, 0x1d, 0xfd, 0x88, 0xd3, 0xab, 0xe9, 0x9d, 0xcf, 0x5e,
	0x90, 0x31, 0x5b, 0x22, 0x73, 0xbe, 0x44, 0xe6, 0xf3, 0x12, 0x99, 0x0f, 0x2b, 0x64, 0xcc, 0x57,
	0xc8, 0x78, 0x5a, 0x21, 0xe3, 0xa6, 0xe5, 0x07, 0xe9, 0x30, 0xf3, 0x30, 0x93, 0x23, 0x32, 0xa0,
	0x29, 0x65, 0x43, 0x1a, 0x84, 0x82, 0x7a, 0xa4, 0xb8, 0x15, 0x5f, 0x92, 0x98, 0x0b, 0x9a, 0x17,
	0xc7, 0xe2, 0x55, 0x94, 0xdf, 0xe3, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x98, 0x15, 0x8b,
	0x46, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Client(ctx context.Context, in *QueryClientRequest, opts ...grpc.CallOption) (*QueryClientResponse, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Client(ctx context.Context, in *QueryClientRequest, opts ...grpc.CallOption) (*QueryClientResponse, error) {
	out := new(QueryClientResponse)
	err := c.cc.Invoke(ctx, "/lcp.service.elc.v1.Query/Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Client(context.Context, *QueryClientRequest) (*QueryClientResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Client(ctx context.Context, req *QueryClientRequest) (*QueryClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Client not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcp.service.elc.v1.Query/Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Client(ctx, req.(*QueryClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lcp.service.elc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Client",
			Handler:    _Query_Client_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcp/service/elc/v1/query.proto",
}

func (m *QueryClientRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClientRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClientRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClientResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClientResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClientResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusState != nil {
		{
			size, err := m.ConsensusState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ClientState != nil {
		{
			size, err := m.ClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryClientRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClientResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientState != nil {
		l = m.ClientState.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ConsensusState != nil {
		l = m.ConsensusState.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryClientRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClientRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClientRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClientResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClientResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClientResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientState == nil {
				m.ClientState = &types.Any{}
			}
			if err := m.ClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusState == nil {
				m.ConsensusState = &types.Any{}
			}
			if err := m.ConsensusState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
