[package]
name = "risc0-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
risc0-build = { version = "=1.2.2", features = ["docker", "unstable"] }
