#!/usr/bin/env bash

set -eox pipefail

source $(cd $(dirname "$0"); pwd)/util

LOAD_DIR=$1
if [ ! -d $LOAD_DIR ];then
  echo "Directory not exists."
  exit 1
fi

shift

for image in "$@"; do
  key=$(createDockerImageCacheKey $image)
  docker load -i "${LOAD_DIR}/${key}"
done
