#!/usr/bin/env bash

set -eox pipefail

source $(cd $(dirname "$0"); pwd)/util

echo $@

SAVE_DIR=$1
if [ ! -d $SAVE_DIR ];then
  echo "Directory not exists."
  mkdir -p $SAVE_DIR
fi

shift

for image in "$@"; do
  key=$(createDockerImageCacheKey $image)
  docker save -o "${SAVE_DIR}/${key}" $image
done
