#!/usr/bin/env bash

source $(cd $(dirname "$0"); pwd)/util

MAX_ATTEMPTS=$1
CONTAINER=$2

attempt_num=1
retry_interval=1

until [[ $(docker inspect --format='{{.State.Health.Status}}' $CONTAINER) == 'healthy' ]]
do
    if (( attempt_num == MAX_ATTEMPTS )); then
        echo "Attempt $attempt_num failed and there are no more attempts left!"
        exit 1
    else
        echo "Attempt $attempt_num failed! Trying again in $retry_interval seconds..."
        sleep $retry_interval
        attempt_num=$(( $attempt_num+1 ))
    fi
done
