[package]
name = "lcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.11", default-features = false }
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
tiny-keccak = { version = "2.0" }
hex-literal = { version = "0.4.1" }
alloy-sol-types = { version = "0.8", default-features = false }
dcap-quote-verifier = { git = "https://github.com/datachainlab/zkdcap", rev = "54ab01c04ca8738b8568b4a6c74a493715af9d2b" }

attestation-report = { path = "../attestation-report", default-features = false }
remote-attestation = { path = "../remote-attestation", default-features = false }
light-client = { path = "../light-client", default-features = false }
crypto = { path = "../crypto", default-features = false }
zkvm = { path = "../zkvm", default-features = false, features = ["verifier"] }

[dev-dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", features = ["extra_traits"] }
ibc = { version = "0.29.0", default-features = false, features = ["serde", "std"] }
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"]}
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }

mock-lc = { path = "../mock-lc" }
store = { path = "../store" }
context = { path = "../context" }
crypto = { path = "../crypto", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "flex-error/std",
    "light-client/std",
    "attestation-report/std",
]
