[package]
name = "lcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.13", default-features = false }
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
tiny-keccak = { version = "1.4" }
hex-literal = { version = "0.4.1" }
alloy-sol-types = { version = "0.6.0", default-features = false }

attestation-report = { path = "../attestation-report", default-features = false }
light-client = { path = "../light-client", default-features = false }
crypto = { path = "../crypto", default-features = false }

[dev-dependencies]
sgx_types = { rev = "v1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", features = ["extra_traits"] }
ibc-primitives = { version = "0.55.0", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"]}
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }

mock-lc = { path = "../mock-lc" }
store = { path = "../store" }
context = { path = "../context" }
crypto = { path = "../crypto", default-features = false, features = ["std"] }

[features]
default = ["std"]
std = [
    "flex-error/std",
    "light-client/std",
    "attestation-report/std",
]
