[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
log = { version = "0.4.8", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
ouroboros = { version = "0.18.4", optional = true }
rocksdb = { version = "0.23.0", optional = true }

[dev-dependencies]
tempfile = "3"
env_logger = "0.11.5"

[features]
default = ["std"]
std = [
    "flex-error/std"
]
rocksdb = [
    "std",
    "dep:rocksdb",
    "ouroboros"
]
