#!/bin/bash
set -eu

DOCKER=docker
SCRIPT_DIR=$(cd $(dirname $0); pwd)
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures

## Setup test fixtures

set +x
rm -rf ${FIXTURES_DIR}
mkdir -p ${FIXTURES_DIR}/tendermint/ibc0
mkdir -p ${FIXTURES_DIR}/tendermint/ibc1
set -x

## copy tendermint's node mnemonic from node container
${DOCKER} cp tendermint-chain0:/root/data/ibc0/key_seed.json  ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json
${DOCKER} cp tendermint-chain1:/root/data/ibc1/key_seed.json  ${FIXTURES_DIR}/tendermint/ibc1/key_seed.json
