#!/bin/bash

set -eux

retry() {
    local -r -i max_attempts="$1"; shift
    local -r cmd="$@"
    local -i attempt_num=1

    until $cmd
    do
        if (( attempt_num == max_attempts ))
        then
            echo "Attempt $attempt_num failed and there are no more attempts left!"
            return 1
        else
            echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
            sleep $(( attempt_num++ ))
        fi
    done
}

RLY="${RLY_BIN} --debug"

CHAINID_ONE=ibc0
RLYKEY=testkey
CHAINID_TWO=ibc1
PATH_NAME=ibc01

$RLY tendermint keys show $CHAINID_ONE $RLYKEY
$RLY tendermint keys show $CHAINID_TWO $RLYKEY

# initialize the light client for {{chain_id}}
retry 5 $RLY lcp-tendermint light init $CHAINID_ONE -f
retry 5 $RLY lcp-tendermint light init $CHAINID_TWO -f

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/path.json

retry 5 $RLY tx clients $PATH_NAME

retry 5 $RLY lcp register-key $PATH_NAME --src=true
retry 5 $RLY lcp register-key $PATH_NAME --src=false

retry 5 $RLY lcp activate-client $PATH_NAME --src=true
retry 5 $RLY lcp activate-client $PATH_NAME --src=false

retry 5 $RLY tx connection $PATH_NAME
retry 5 $RLY tx channel $PATH_NAME
