[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx-urts = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs" }
sgx-types = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs", features = ["urts"] }
log = "0.4.8"
once_cell = "1.15.0"
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["serde", "alloc"] }

lcp-types = { path = "../types" }
ocall-commands = { path = "../ocall-commands" }
ocall-handler = { path = "../ocall-handler", default-features = false }

[features]
default = []
rocksdb = [
    "ocall-handler/rocksdb"
]
test = []