[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.1.3", default-features = false, features = ["client", "prove"] }
risc0-zkp = { version = "=1.1.3", default-features = false }
flex-error = { version = "0.4.4", default-features = false }

[features]
default = []
cuda = ["risc0-zkvm/cuda"]
