[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.1.3", default-features = false, features = ["client"] }
flex-error = { version = "0.4.4", default-features = false }

methods = { path = "../../methods" }

[features]
default = ["cuda"]
cuda = ["risc0-zkvm/cuda"]
