// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relay/lcp/config.proto

package relay

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	OriginProver      *types.Any `protobuf:"bytes,1,opt,name=origin_prover,json=originProver,proto3" json:"origin_prover,omitempty"`
	LcpServiceAddress string     `protobuf:"bytes,2,opt,name=lcp_service_address,json=lcpServiceAddress,proto3" json:"lcp_service_address,omitempty"`
	Mrenclave         string     `protobuf:"bytes,3,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	ElcClientId       string     `protobuf:"bytes,4,opt,name=elc_client_id,json=elcClientId,proto3" json:"elc_client_id,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a4a2b8a20ab834, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.lcp.config.ProverConfig")
}

func init() { proto.RegisterFile("relay/lcp/config.proto", fileDescriptor_77a4a2b8a20ab834) }

var fileDescriptor_77a4a2b8a20ab834 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x6a, 0xeb, 0x30,
	0x14, 0x86, 0xad, 0x7b, 0x4b, 0x21, 0x4a, 0x32, 0xd4, 0x0d, 0xc5, 0x0d, 0x45, 0x84, 0xd0, 0x21,
	0x93, 0x04, 0xed, 0xd4, 0x31, 0xc9, 0xd4, 0xad, 0xa4, 0x5b, 0x17, 0x23, 0x1f, 0x9f, 0x28, 0x02,
	0x45, 0x32, 0xb2, 0x13, 0xc8, 0x5b, 0xf4, 0x7d, 0xfa, 0x02, 0x19, 0x33, 0x76, 0x6c, 0xed, 0x17,
	0x29, 0x91, 0x28, 0xdd, 0x74, 0xfe, 0xff, 0xd3, 0x07, 0xe7, 0xd0, 0x1b, 0x8f, 0x46, 0x1e, 0x84,
	0x81, 0x4a, 0x80, 0xb3, 0x6b, 0xad, 0x78, 0xe5, 0x5d, 0xe3, 0xd2, 0x71, 0xc8, 0xd1, 0x9f, 0xc7,
	0x3d, 0xfa, 0x9a, 0x1b, 0xa8, 0x78, 0x24, 0xc6, 0x23, 0xe5, 0x94, 0x0b, 0x98, 0x38, 0xbf, 0xe2,
	0x8f, 0xf1, 0xad, 0x72, 0x4e, 0x19, 0x14, 0x61, 0x2a, 0x76, 0x6b, 0x21, 0xed, 0x21, 0x56, 0xd3,
	0x0f, 0x42, 0x07, 0x2f, 0xc1, 0xb3, 0x0c, 0x86, 0xf4, 0x89, 0x0e, 0x9d, 0xd7, 0x4a, 0xdb, 0x3c,
	0xea, 0x33, 0x32, 0x21, 0xb3, 0xfe, 0xc3, 0x88, 0x47, 0x07, 0xff, 0x75, 0xf0, 0xb9, 0x3d, 0xac,
	0x06, 0x11, 0x8d, 0x82, 0x94, 0xd3, 0x6b, 0x03, 0x55, 0x5e, 0xa3, 0xdf, 0x6b, 0xc0, 0x5c, 0x96,
	0xa5, 0xc7, 0xba, 0xce, 0xfe, 0x4d, 0xc8, 0xac, 0xb7, 0xba, 0x32, 0x50, 0xbd, 0xc6, 0x66, 0x1e,
	0x8b, 0xf4, 0x8e, 0xf6, 0xb6, 0x1e, 0x2d, 0x18, 0xb9, 0xc7, 0xec, 0x7f, 0xa0, 0xfe, 0x82, 0x74,
	0x4a, 0x87, 0x68, 0x20, 0x07, 0xa3, 0xd1, 0x36, 0xb9, 0x2e, 0xb3, 0x8b, 0x40, 0xf4, 0xd1, 0xc0,
	0x32, 0x64, 0xcf, 0xe5, 0x62, 0x71, 0xfc, 0x66, 0xc9, 0xb1, 0x65, 0xe4, 0xd4, 0x32, 0xf2, 0xd5,
	0x32, 0xf2, 0xde, 0xb1, 0xe4, 0xd4, 0xb1, 0xe4, 0xb3, 0x63, 0xc9, 0xdb, 0xbd, 0xd2, 0xcd, 0x66,
	0x57, 0x70, 0x70, 0x5b, 0x51, 0xca, 0x46, 0xc2, 0x46, 0x6a, 0x6b, 0x64, 0x11, 0x4e, 0xaa, 0x9c,
	0x08, 0x77, 0x2c, 0x2e, 0xc3, 0x46, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x13, 0x3d,
	0x9d, 0x6f, 0x01, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ElcClientId) > 0 {
		i -= len(m.ElcClientId)
		copy(dAtA[i:], m.ElcClientId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ElcClientId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LcpServiceAddress) > 0 {
		i -= len(m.LcpServiceAddress)
		copy(dAtA[i:], m.LcpServiceAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LcpServiceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.OriginProver != nil {
		{
			size, err := m.OriginProver.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OriginProver != nil {
		l = m.OriginProver.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.LcpServiceAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.ElcClientId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginProver", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OriginProver == nil {
				m.OriginProver = &types.Any{}
			}
			if err := m.OriginProver.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcpServiceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LcpServiceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElcClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElcClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
