[package]
name = "enclave-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx-types = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs", features = ["urts"] }
sgx-urts = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs" }
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["serde", "alloc"] }
log = "0.4.8"
flex-error = { version = "0.4.4" }

lcp-types = { path = "../types" }
commitments = { path = "../commitments" }
ecall-commands = { path = "../ecall-commands", features = ["std"] }
keymanager = { path = "../keymanager" }
store = { path = "../store" }
host = { path = "../host" }
attestation-report = { path = "../attestation-report" }
lcp-proto = { path = "../../proto", features = ["server"] }

[features]
default = ["std"]
std = [
    "flex-error/std"
]
rocksdb = [
    "host/rocksdb"
]
