[package]
name = "mock-lc"
version = "0.1.0"
edition = "2021"

[dependencies]
ibc-primitives = { version = "0.55.0", default-features = false }
ibc-core-client = { version = "0.55.0", default-features = false, features = ["serde"] }
ibc-core-host-types = { version = "0.55.0", default-features = false }
ibc-core-commitment-types = { version = "0.55.0", default-features = false }
ibc-proto = { version = "0.47.1", default-features = false }
serde = { version = "1.0.184", default-features = false, features = ["alloc", "derive"] }
flex-error = { version = "0.4.4", default-features = false }

light-client = { path = "../light-client", default-features = false, features = ["ibc"] }

[dev-dependencies]
serde_json = { version = "1.0", default-features = false }
