[package]
name = "enclave-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
sgx-types = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs" }
sgx-trts = { rev = "e860e34", git = "https://github.com/datachainlab/sgx-sdk-rs" }
log = { version = "0.4.8", default-features = false }
