// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lcp/service/enclave/v1/query.proto

package enclave

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAttestedVerificationReportRequest struct {
}

func (m *QueryAttestedVerificationReportRequest) Reset() {
	*m = QueryAttestedVerificationReportRequest{}
}
func (m *QueryAttestedVerificationReportRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestedVerificationReportRequest) ProtoMessage()    {}
func (*QueryAttestedVerificationReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b0894e959bbc62, []int{0}
}
func (m *QueryAttestedVerificationReportRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestedVerificationReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestedVerificationReportRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestedVerificationReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestedVerificationReportRequest.Merge(m, src)
}
func (m *QueryAttestedVerificationReportRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestedVerificationReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestedVerificationReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestedVerificationReportRequest proto.InternalMessageInfo

type QueryAttestedVerificationReportResponse struct {
	EnclaveAddress []byte `protobuf:"bytes,1,opt,name=enclave_address,json=enclaveAddress,proto3" json:"enclave_address,omitempty"`
	Report         string `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SigningCert    []byte `protobuf:"bytes,4,opt,name=signing_cert,json=signingCert,proto3" json:"signing_cert,omitempty"`
}

func (m *QueryAttestedVerificationReportResponse) Reset() {
	*m = QueryAttestedVerificationReportResponse{}
}
func (m *QueryAttestedVerificationReportResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestedVerificationReportResponse) ProtoMessage()    {}
func (*QueryAttestedVerificationReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b0894e959bbc62, []int{1}
}
func (m *QueryAttestedVerificationReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestedVerificationReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestedVerificationReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestedVerificationReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestedVerificationReportResponse.Merge(m, src)
}
func (m *QueryAttestedVerificationReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestedVerificationReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestedVerificationReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestedVerificationReportResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryAttestedVerificationReportRequest)(nil), "lcp.service.enclave.v1.QueryAttestedVerificationReportRequest")
	proto.RegisterType((*QueryAttestedVerificationReportResponse)(nil), "lcp.service.enclave.v1.QueryAttestedVerificationReportResponse")
}

func init() {
	proto.RegisterFile("lcp/service/enclave/v1/query.proto", fileDescriptor_17b0894e959bbc62)
}

var fileDescriptor_17b0894e959bbc62 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0x4b, 0x3b, 0x31,
	0x18, 0xc6, 0x2f, 0xff, 0xbf, 0x16, 0x1a, 0x8b, 0x42, 0x90, 0x72, 0x14, 0x09, 0xb5, 0x83, 0xed,
	0x20, 0x09, 0xd5, 0x5d, 0xa9, 0x6e, 0x6e, 0xde, 0xe0, 0xe0, 0x52, 0xd2, 0xdc, 0xeb, 0x35, 0x70,
	0x5e, 0xae, 0x49, 0xee, 0xa0, 0xdf, 0xc2, 0x2f, 0xe0, 0xec, 0xe0, 0x17, 0xe9, 0xd8, 0xd1, 0x51,
	0xdb, 0x2f, 0x22, 0x77, 0x8d, 0xb8, 0x28, 0x8a, 0x5b, 0xde, 0x87, 0xdf, 0x43, 0x5e, 0x9e, 0xf7,
	0xc1, 0xbd, 0x54, 0xe6, 0xdc, 0x82, 0x29, 0x95, 0x04, 0x0e, 0x99, 0x4c, 0x45, 0x09, 0xbc, 0x1c,
	0xf2, 0x59, 0x01, 0x66, 0xce, 0x72, 0xa3, 0x9d, 0x26, 0xed, 0x54, 0xe6, 0xcc, 0x33, 0xcc, 0x33,
	0xac, 0x1c, 0x76, 0xf6, 0x13, 0x9d, 0xe8, 0x1a, 0xe1, 0xd5, 0x6b, 0x43, 0xf7, 0x06, 0xf8, 0xe8,
	0xba, 0x32, 0x8f, 0x9c, 0x03, 0xeb, 0x20, 0xbe, 0x01, 0xa3, 0xee, 0x94, 0x14, 0x4e, 0xe9, 0x2c,
	0x82, 0x5c, 0x1b, 0x17, 0xc1, 0xac, 0x00, 0xeb, 0x7a, 0xcf, 0x08, 0xf7, 0x7f, 0x44, 0x6d, 0xae,
	0x33, 0x0b, 0xa4, 0x8f, 0xf7, 0xfc, 0xcf, 0x63, 0x11, 0xc7, 0x06, 0xac, 0x0d, 0x51, 0x17, 0x0d,
	0x5a, 0xd1, 0xae, 0x97, 0x47, 0x1b, 0x95, 0xb4, 0x71, 0xc3, 0xd4, 0xd6, 0xf0, 0x5f, 0x17, 0x0d,
	0x9a, 0x91, 0x9f, 0xc8, 0x01, 0x6e, 0x5a, 0x95, 0x64, 0xc2, 0x15, 0x06, 0xc2, 0xff, 0xb5, 0xf5,
	0x53, 0x20, 0x87, 0xb8, 0x55, 0x0d, 0x2a, 0x4b, 0xc6, 0x12, 0x8c, 0x0b, 0xb7, 0x6a, 0x60, 0xc7,
	0x6b, 0x97, 0x60, 0xdc, 0xc9, 0x13, 0xc2, 0xdb, 0xf5, 0xb6, 0xe4, 0x11, 0xe1, 0xce, 0xf7, 0x2b,
	0x93, 0x33, 0xf6, 0x75, 0x5e, 0xec, 0x77, 0xb1, 0x74, 0xce, 0xff, 0xec, 0xdf, 0x64, 0x75, 0x71,
	0xb5, 0x78, 0xa3, 0xc1, 0x62, 0x45, 0xd1, 0x72, 0x45, 0xd1, 0xeb, 0x8a, 0xa2, 0x87, 0x35, 0x0d,
	0x96, 0x6b, 0x1a, 0xbc, 0xac, 0x69, 0x70, 0x7b, 0x9c, 0x28, 0x37, 0x2d, 0x26, 0x4c, 0xea, 0x7b,
	0x1e, 0x0b, 0x27, 0xe4, 0x54, 0xa8, 0x2c, 0x15, 0x13, 0x5e, 0x35, 0x21, 0xd1, 0xdc, 0x40, 0x2a,
	0xe6, 0x1f, 0x55, 0x98, 0x34, 0xea, 0xa3, 0x9e, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x11, 0xf2,
	0xd5, 0x68, 0x28, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	AttestedVerificationReport(ctx context.Context, in *QueryAttestedVerificationReportRequest, opts ...grpc.CallOption) (*QueryAttestedVerificationReportResponse, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AttestedVerificationReport(ctx context.Context, in *QueryAttestedVerificationReportRequest, opts ...grpc.CallOption) (*QueryAttestedVerificationReportResponse, error) {
	out := new(QueryAttestedVerificationReportResponse)
	err := c.cc.Invoke(ctx, "/lcp.service.enclave.v1.Query/AttestedVerificationReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	AttestedVerificationReport(context.Context, *QueryAttestedVerificationReportRequest) (*QueryAttestedVerificationReportResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AttestedVerificationReport(ctx context.Context, req *QueryAttestedVerificationReportRequest) (*QueryAttestedVerificationReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestedVerificationReport not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AttestedVerificationReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestedVerificationReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AttestedVerificationReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lcp.service.enclave.v1.Query/AttestedVerificationReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AttestedVerificationReport(ctx, req.(*QueryAttestedVerificationReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lcp.service.enclave.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttestedVerificationReport",
			Handler:    _Query_AttestedVerificationReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcp/service/enclave/v1/query.proto",
}

func (m *QueryAttestedVerificationReportRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestedVerificationReportRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestedVerificationReportRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAttestedVerificationReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestedVerificationReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestedVerificationReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SigningCert) > 0 {
		i -= len(m.SigningCert)
		copy(dAtA[i:], m.SigningCert)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SigningCert)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Report) > 0 {
		i -= len(m.Report)
		copy(dAtA[i:], m.Report)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Report)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EnclaveAddress) > 0 {
		i -= len(m.EnclaveAddress)
		copy(dAtA[i:], m.EnclaveAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EnclaveAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAttestedVerificationReportRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAttestedVerificationReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EnclaveAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Report)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SigningCert)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAttestedVerificationReportRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestedVerificationReportRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestedVerificationReportRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestedVerificationReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestedVerificationReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestedVerificationReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnclaveAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnclaveAddress = append(m.EnclaveAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.EnclaveAddress == nil {
				m.EnclaveAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Report = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningCert", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigningCert = append(m.SigningCert[:0], dAtA[iNdEx:postIndex]...)
			if m.SigningCert == nil {
				m.SigningCert = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
