[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.9", default-features = false }
tonic-reflection = { version = "0.9" }
tokio = { version = "1.0", features = ["full"] }
anyhow = { version = "1.0.56" }

lcp-types = { path = "../types" }
crypto = { path = "../crypto" }
enclave-api = { path = "../enclave-api" }
lcp-proto = { path = "../../proto", default-features = false, features = ["server"] }
store = { path = "../store", default-features = false }
attestation-report = { path = "../attestation-report" }
